### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dateFormat' of undefined 

### ISSUE THREAD

**Issue by mrchess** [zpaulovics/datetimepicker-rails#19] opened 2014-08-19 05:22 UTC
When doing 

`<%= f.input :start_date_time, :as => :datetime_picker %>`

it throws this error. Not sure why. Any thoughts?

Using the latest of everything... 3.0.2+ and latest moment.js.

**Comment by hypsol** [comment] 2015-01-04 04:44
I ran into this problem too.  I agree with @Silex and @schmidtg in that when .datetimepicker() binds to, for example, div.datepicker, it creates the Date Picker which itself has a div.datepicker.  I have found two solutions: 1) change the binding from...
```javascript
$(document).on('ready page:change', function() {...} )
```
to...
```javascript
$(document).on('ready page:load', function() {...} )
```
so that the div.datepicker selection only happens once (on page load); 2) change the class name that jQuery is looking for, for example...
```javascript
$('.not_datepicker_anymore').datetimepicker({...})
```
I went with the first solution, as I knew I would not be dynamically creating any fields that need a datepicker attached.  But imho, simply changing the class name is a better long term solution.

**Comment by gshilin** [comment] 2015-01-07 17:17
I ran into it too. This is my solution. First I changed (in all three inputs):
```ruby
template.content_tag :div, class: 'input-group date timepicker'
```
to
```ruby
template.content_tag :div, class: 'input-group date timepicker thepicker'
```
and the binding (all three) from
```javascript
$('.timepicker').datetimepicker({
```
to
```javascript
$('.timepicker.thepicker').datetimepicker({
```

**Comment by monteirobrena** [comment] 2015-02-01 01:46
Thank you @wtfiwtz.

The solution for me was the same. Just add the below code in `bootstrap-datetimepicker.js`:

    if (eData === undefined) {
        return;
    }

**Comment by zpaulovics** [comment] 2015-02-01 06:01
Hi monteirobrena,

Unfortunately I can not reproduce the issue. Yesterday I updated the picker to 4.0.0.RC1 (**available in branch eonasdan**), which is based on the bootstrap-datetimepicker version 4.0.0. That version of the library went over a major refactoring. Please, test your code with the new version and let me know the result.
Zoltan

**Comment by Nerian** [comment] 2015-02-01 17:31
@zpaulovics Hi, I am just starting using this gem. Should we be using Master or the eonasdan branch?

**Comment by zpaulovics** [comment] 2015-02-02 05:21
Hi,

The master branch always has the latest stable version of the gem. The branch eonasdan is developed/updated and when it becomes stable merged to master. For instance, this particular moment eonasdan is upgraded to 4.0.0, but it in RC1 state now, because I am waiting for a pull request to be accepted on bootstrap-datetimepicker. The current upgrade expected to merge to master in a week or so.

So the short answer is: use master for production, use eonasdan branch for new development.

I need some time to consider and answer your further questions. Please, be patient.

Zoltan

**Comment by zpaulovics** [comment] 2015-02-02 09:59
Hi Nerian,

Your range picker seems attractive to me. I'd like to see a pull request with your solution.
The pull request should be raised on eonasdan branch. Please, modify the generator accordingly to extend the pickers and create the initializer based on your template of wrapper.

I do not like to use the https://github.com/TrevorS/bootstrap3-datetimepicker-rails gem, as you suggested. There are more than one reasons: 
 - Before any upgrade to a new version of boostrarp-datetimepicker and Momentjs I need to check the compatibility with its public interface and do the required modification in my gem, as it has happened now when I upgrade to version 4.0.0. and also at upgrades before that.
 - The current solution have the flexibility to customize the generated picker on two levels without taching the gem area: 1. to customize the picker.js, 2. to customize the input fields definitions. That is why they are placed in the application tree and not on the gem area.
  - To handle the asset pipeline does not offer me to much added value when managing and maintaining this gem, but would create one more outside artifact to syncronize to. If the dependencies version would become incompatible for a while, my gem from, master branch, could generate code that is not working properly.      

Zoltan

**Closed** 2015-02-02 19:50 UTC

**Comment by quangthinhnguyen** [comment] 2016-09-04 09:35
You can add 
```
if (eData === null) {
                return;
            }
```
Before
```
if (eData.dateFormat !== undefined) {
                picker.options.format = eData.dateFormat;
            }
```
